const List = [{
    id: 122,
    parentId: null,
    code: "brgyRGGuYxNxtLWnNwaVobrgyRGGuYxNxtLWnNwaVobrgyRGGuYxNxtLWnNwaVo",
    name: "测试发动机",
    describe: null,
    deviceNum: -1,
    createTime: "2021-12-08 15:11:34",
    productId: 35,
    productCode: "q_car_engine",
    productName: "青岛发动机",
    productAgreement: 1,
    projectId: 12,
    projectCode: "SWmMYQBkSBPAFzKP5riwnb",
    projectName: "青岛POC",
    keepAlive: true,
    activeTime: "2021-12-08 15:35:58",
    lastMessageTime: "2021-12-14 09:35:19",
    format: 1,
    formatName: "JSON",
    productTypeName: "设备",
    productLinkName: "直连",
    productAgreementName: "MQTT",
  },
  {
    id: 121,
    parentId: null,
    code: "9ADWqUnxcJ7BLFomqJmmfA",
    name: "青岛发动机001",
    describe: null,
    deviceNum: -1,
    createTime: "2021-12-08 10:35:11",
    productId: 35,
    productCode: "q_car_engine",
    productName: "青岛发动机",
    productAgreement: 1,
    projectId: 10,
    projectCode: "HBW7u4MA7sZVTxEE1Nemr",
    projectName: "青烟厂智能安全生产监管平台",
    keepAlive: false,
    activeTime: "2021-12-08 10:39:48",
    lastMessageTime: null,
    format: 1,
    formatName: "JSON",
    productTypeName: "设备",
    productLinkName: "直连",
    productAgreementName: "MQTT",
  },
  {
    id: 120,
    parentId: null,
    code: "CsX6DuyVLCzWvnXfhZoupi",
    name: "test_device_20211201",
    describe: "test_device",
    deviceNum: -1,
    createTime: "2021-12-01 11:21:06",
    productId: 34,
    productCode: "test_product_id",
    productName: "新建测试",
    productAgreement: 1,
    projectId: 11,
    projectCode: "9yaA1AhmecGrqSZH2LWGXT",
    projectName: "test",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 1,
    formatName: "JSON",
    productTypeName: "设备",
    productLinkName: "直连",
    productAgreementName: "MQTT",
  },
  {
    id: 118,
    parentId: 15,
    code: "JRLhr4N6yUqRSwAj7owSwF",
    name: "onvif-45",
    describe: null,
    deviceNum: -1,
    createTime: "2021-11-25 11:50:13",
    productId: 28,
    productCode: "test_onvif",
    productName: "ONVIF摄像头",
    productAgreement: 7,
    projectId: 2,
    projectCode: "pro",
    projectName: "安全生产项目",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 21,
    formatName: "视频流",
    productTypeName: "摄像头",
    productLinkName: "非直连",
    productAgreementName: "ONVIF",
  },
  {
    id: 117,
    parentId: 110,
    code: "2q7bEQQbPvTMZjXn8keimm",
    name: "视频网关测试",
    describe: null,
    deviceNum: -1,
    createTime: "2021-11-23 17:08:40",
    productId: 28,
    productCode: "test_onvif",
    productName: "ONVIF摄像头",
    productAgreement: 7,
    projectId: 4,
    projectCode: "kwHr993yU/TG8zIo1NpF+A==",
    projectName: "光伏能源POC",
    keepAlive: false,
    activeTime: "2021-11-24 09:35:39",
    lastMessageTime: null,
    format: 21,
    formatName: "视频流",
    productTypeName: "摄像头",
    productLinkName: "非直连",
    productAgreementName: "ONVIF",
  },
  {
    id: 116,
    parentId: 94,
    code: "W14EbKhe7WuqxUrRip84NG",
    name: "测试",
    describe: null,
    deviceNum: -1,
    createTime: "2021-11-19 15:51:25",
    productId: 4,
    productCode: "camera",
    productName: "摄像头产品",
    productAgreement: 3,
    projectId: 10,
    projectCode: "HBW7u4MA7sZVTxEE1Nemr",
    projectName: "青烟厂智能安全生产监管平台",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 21,
    formatName: "视频流",
    productTypeName: "摄像头",
    productLinkName: "非直连",
    productAgreementName: "RTSP",
  },
  {
    id: 115,
    parentId: 110,
    code: "2UeFG3Kr1NNg9VeKtW4nQu",
    name: "测试电机",
    describe: null,
    deviceNum: -1,
    createTime: "2021-11-15 17:14:56",
    productId: 31,
    productCode: "electric_motor",
    productName: "电机-非直连",
    productAgreement: 2,
    projectId: 4,
    projectCode: "kwHr993yU/TG8zIo1NpF+A==",
    projectName: "光伏能源POC",
    keepAlive: false,
    activeTime: "2021-11-15 18:01:32",
    lastMessageTime: null,
    format: 2,
    formatName: "二进制",
    productTypeName: "设备",
    productLinkName: "非直连",
    productAgreementName: "MODBUS",
  },
  {
    id: 113,
    parentId: 110,
    code: "8VEmaHqa6CBd83bue9q2VW",
    name: "逆变器",
    describe: null,
    deviceNum: -1,
    createTime: "2021-11-15 16:57:21",
    productId: 17,
    productCode: "huawei_poc",
    productName: "光伏能源逆变器",
    productAgreement: 2,
    projectId: 4,
    projectCode: "kwHr993yU/TG8zIo1NpF+A==",
    projectName: "光伏能源POC",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 2,
    formatName: "二进制",
    productTypeName: "设备",
    productLinkName: "非直连",
    productAgreementName: "MODBUS",
  },
  {
    id: 110,
    parentId: null,
    code: "5GjMQV3J1coRGqqCC6v43J",
    name: "光伏能源边缘节点",
    describe: null,
    deviceNum: 3,
    createTime: "2021-11-15 15:34:52",
    productId: 3,
    productCode: "edge",
    productName: "边缘计算平台产品",
    productAgreement: 1,
    projectId: 4,
    projectCode: "kwHr993yU/TG8zIo1NpF+A==",
    projectName: "光伏能源POC",
    keepAlive: true,
    activeTime: "2021-11-15 15:37:04",
    lastMessageTime: null,
    format: 1,
    formatName: "JSON",
    productTypeName: "边缘节点",
    productLinkName: "直连",
    productAgreementName: "MQTT",
  },
  {
    id: 109,
    parentId: 3,
    code: "GComF1UNrhRBzXxs88mTUv",
    name: "RTSP测试",
    describe: null,
    deviceNum: -1,
    createTime: "2021-11-11 16:51:50",
    productId: 4,
    productCode: "camera",
    productName: "摄像头产品",
    productAgreement: 3,
    projectId: 1,
    projectCode: "car",
    projectName: "新概念汽车项目",
    keepAlive: false,
    activeTime: "2021-11-18 10:30:50",
    lastMessageTime: null,
    format: 21,
    formatName: "视频流",
    productTypeName: "摄像头",
    productLinkName: "非直连",
    productAgreementName: "RTSP",
  },
  {
    id: 108,
    parentId: 3,
    code: "83mtoX7xi7VrJgvGRnDkbk",
    name: "ONVIF设备测试",
    describe: null,
    deviceNum: -1,
    createTime: "2021-11-09 10:39:25",
    productId: 28,
    productCode: "test_onvif",
    productName: "ONVIF摄像头",
    productAgreement: 7,
    projectId: 1,
    projectCode: "car",
    projectName: "新概念汽车项目",
    keepAlive: false,
    activeTime: "2021-12-03 16:39:12",
    lastMessageTime: null,
    format: 21,
    formatName: "视频流",
    productTypeName: "摄像头",
    productLinkName: "非直连",
    productAgreementName: "ONVIF",
  },
  {
    id: 106,
    parentId: 105,
    code: "DviMqpWYRMk5C4iXRnad2s",
    name: "QDTEST-1",
    describe: null,
    deviceNum: -1,
    createTime: "2021-11-01 16:11:48",
    productId: 6,
    productCode: "modbus1",
    productName: "Modbus产品-001",
    productAgreement: 2,
    projectId: 10,
    projectCode: "HBW7u4MA7sZVTxEE1Nemr",
    projectName: "青烟厂智能安全生产监管平台",
    keepAlive: false,
    activeTime: "2021-11-10 09:56:22",
    lastMessageTime: null,
    format: 2,
    formatName: "二进制",
    productTypeName: "设备",
    productLinkName: "非直连",
    productAgreementName: "MODBUS",
  },
  {
    id: 105,
    parentId: null,
    code: "CJjh6jUDSC7P9qHqjrEa5o",
    name: "QDTEST",
    describe: null,
    deviceNum: 1,
    createTime: "2021-11-01 14:41:38",
    productId: 26,
    productCode: "dataGetway_chenjun",
    productName: "青烟厂安全生产数据采集网关",
    productAgreement: 1,
    projectId: 10,
    projectCode: "HBW7u4MA7sZVTxEE1Nemr",
    projectName: "青烟厂智能安全生产监管平台",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 1,
    formatName: "JSON",
    productTypeName: "网关",
    productLinkName: "直连",
    productAgreementName: "MQTT",
  },
  {
    id: 97,
    parentId: null,
    code: "WY239ZGek5KjijpbAoZp4u",
    name: "非PTZ摄像头",
    describe: null,
    deviceNum: -1,
    createTime: "2021-10-25 15:58:04",
    productId: 27,
    productCode: "gb28181_test",
    productName: "GB28181摄像头",
    productAgreement: 6,
    projectId: 1,
    projectCode: "car",
    projectName: "新概念汽车项目",
    keepAlive: true,
    activeTime: "2021-10-25 16:01:07",
    lastMessageTime: null,
    format: 21,
    formatName: "视频流",
    productTypeName: "摄像头",
    productLinkName: "直连",
    productAgreementName: "GB28181",
  },
  {
    id: 96,
    parentId: null,
    code: "7D7tHfZZ5EuBMKiL3N1pGw",
    name: "gb28181测试1",
    describe: null,
    deviceNum: -1,
    createTime: "2021-10-19 10:09:49",
    productId: 27,
    productCode: "gb28181_test",
    productName: "GB28181摄像头",
    productAgreement: 6,
    projectId: 1,
    projectCode: "car",
    projectName: "新概念汽车项目",
    keepAlive: true,
    activeTime: "2021-10-21 17:11:54",
    lastMessageTime: null,
    format: 21,
    formatName: "视频流",
    productTypeName: "摄像头",
    productLinkName: "直连",
    productAgreementName: "GB28181",
  },
  {
    id: 95,
    parentId: null,
    code: "6Xsq3BKGaT2ZK5r1CBdwWV",
    name: "门禁",
    describe: "出入口平台系统，包含开、关门、取消、报警等。",
    deviceNum: 0,
    createTime: "2021-10-15 17:20:06",
    productId: 26,
    productCode: "dataGetway_chenjun",
    productName: "青烟厂安全生产数据采集网关",
    productAgreement: 1,
    projectId: 10,
    projectCode: "HBW7u4MA7sZVTxEE1Nemr",
    projectName: "青烟厂智能安全生产监管平台",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 1,
    formatName: "JSON",
    productTypeName: "网关",
    productLinkName: "直连",
    productAgreementName: "MQTT",
  },
  {
    id: 94,
    parentId: null,
    code: "6T2Nck1r9HGvMXUSwqVbBR",
    name: "周界",
    describe: "光纤周界监测系统",
    deviceNum: 1,
    createTime: "2021-10-15 17:03:53",
    productId: 26,
    productCode: "dataGetway_chenjun",
    productName: "青烟厂安全生产数据采集网关",
    productAgreement: 1,
    projectId: 10,
    projectCode: "HBW7u4MA7sZVTxEE1Nemr",
    projectName: "青烟厂智能安全生产监管平台",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 1,
    formatName: "JSON",
    productTypeName: "网关",
    productLinkName: "直连",
    productAgreementName: "MQTT",
  },
  {
    id: 88,
    parentId: 42,
    code: "64n66DkTfxakMZiBYfLYmA",
    name: "测试设备2",
    describe: null,
    deviceNum: -1,
    createTime: "2021-10-08 15:20:16",
    productId: 13,
    productCode: "dpi_tcp_am",
    productName: "测试TCP_am",
    productAgreement: 4,
    projectId: 2,
    projectCode: "pro",
    projectName: "安全生产项目",
    keepAlive: false,
    activeTime: "2021-10-28 17:40:16",
    lastMessageTime: null,
    format: 11,
    formatName: "私有协议",
    productTypeName: "设备",
    productLinkName: "非直连",
    productAgreementName: "TCP",
  },
  {
    id: 87,
    parentId: 42,
    code: "MU4BdyTAUzpoyVE51kBKKH",
    name: "测试设备1",
    describe: null,
    deviceNum: -1,
    createTime: "2021-10-08 15:19:27",
    productId: 14,
    productCode: "zedx_pro",
    productName: "山东POC",
    productAgreement: 1,
    projectId: 2,
    projectCode: "pro",
    projectName: "安全生产项目",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 1,
    formatName: "JSON",
    productTypeName: "设备",
    productLinkName: "非直连",
    productAgreementName: "MQTT",
  },
  {
    id: 85,
    parentId: null,
    code: "6x1j5Sw5KHvuXPTJ5uNGzn",
    name: "燃气管网",
    describe: null,
    deviceNum: 0,
    createTime: "2021-10-08 11:16:00",
    productId: 25,
    productCode: "ZHNYDLSJCJCP",
    productName: "综合能源-电力数据采集产品",
    productAgreement: 1,
    projectId: 9,
    projectCode: "YWwJWwJxgGR3goAgiFJyfp",
    projectName: "D-AIOT平台全局测试",
    keepAlive: false,
    activeTime: null,
    lastMessageTime: null,
    format: 1,
    formatName: "JSON",
    productTypeName: "网关",
    productLinkName: "直连",
    productAgreementName: "MQTT",
  },
]

export default List;